name: Update Files and Create Zip

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set VERSION
      run: |
        VERSION=$(head -n 4 module.prop | tail -n 1 | sed 's/.\{12\}//')
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Update module.prop
      run: |
        sed -i "3s/[0-9]\+/$VERSION/" ./module.prop

    - name: Remove old zip file
      run: |
        rm -f ./mark2_5000_v${VERSION}.zip

    - name: Compile dtbo files
      run: |
        dtc -@ -I dts -O dtb -o ./dtbo/origin_pdx203.dtbo ./dts/origin_pdx203.dts &> /dev/null
        dtc -@ -I dts -O dtb -o ./dtbo/overlay_pdx203.dtbo ./dts/overlay_pdx203.dts &> /dev/null
        
    - name: Create zip file
      run: |
        zip -qr mark2_5000_v${VERSION}.zip ./ -i "bin/*" -i "dtbo/*.dtbo" -i "META-INF/*" -i "system/*" -i "customize.sh" -i "module.prop" -i "uninstall.sh"
