name: Build and Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up environment
        run: sudo apt-get update && sudo apt-get install -y zip

      - name: Run build script
        run: sh build.sh
